version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm
    commit-message:
      prefix: deps
      include: scope
    groups:
      docs-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "09:30"
      timezone: Asia/Shanghai
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: ci
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"
